#include <SoftCores/Util/File.h>
#include <fstream>

#include "SoftCores/Enums.h"

using namespace SoftCores::Util;


void File::Open(const char *filename, const std::ios_base::openmode mode)
{
	file.open(filename, mode);
}

void File::Close()
{
	file.close();
}

bool File::IsOpen() const
{
	return (file.is_open());
}

bool File::Exists(const char *filename)
{
	const std::ifstream	input(filename);
	return (input.good());
}


// Generated by GPT5.3
std::string File::WideToUTF8(const wchar_t *wstr)
{
	int	size_needed;

	size_needed = WideCharToMultiByte(
		CP_UTF8, 0,
		wstr, -1,
		nullptr, 0,
		nullptr, nullptr
		);

	std::string result(size_needed - 1, 0); // exclude null terminator

	WideCharToMultiByte(
		CP_UTF8, 0,
		wstr, -1,
		result.data(), size_needed,
		nullptr, nullptr
	);

	return (result);
}
