[DEBUG]
ENABLE_LOGGING=1

[IMMERSION]
# overrides all configuration of _FX, 0 will ensure vanilla red dead fx stays on, 1 enable this mod overrides
IMMERSION_FX=1

# 1 = enable, 0 = disable
EMPTY_HEALTH_FX=1
EMPTY_STAMINA_FX=1
EMPTY_DEADEYE_FX=1
OVERPOWER_FX=1
DUEL_FX=1
DEADEYE_FX=1
EAGLEEYE_FX=1
HUDWHEEL_FX=0
KILLCAM_FX=0
PEDKILL_FX=0
DEATH_FX=0
FAIL_FX=0

PICKUPS_GLOW=0
OBJECTS_GLOW=0
HOSTILE_BLIP=0
HOSTILE_BLIP_ON_MISSION=0
DEADEYE_RELOAD=0
SLEEP_STAMINA_ONLY=1
BATH_DEADEYE_ONLY=1
HEADHSHOT_IMMUNITY=0

# in milliseconds in real life time 1000 ms - 1 sec
[TIMERS]
CORE_DEPLETION=120000 # depletion of all cores over time
HEALTH_PENALTY=8000 # penalty to health outer core when main core is empty
TEMPERATURE_PENALTY=8000 # penalty applied to player when cold or hot
AI_HEALTH_REGEN=8000 # ai health regen over time
AIMING_DEPLETION = 500 # depletion of stamina & deadeye during aiming

# percentage based 0 - 100
[CORE_MODIFIER]
# drain stamina and deadeye during aiming
AIM_PENALTY=1

# hp outer core regen
# 0 means no regen at all
# still no regen at all when certain conditions are met, like in combat & not in cover
PLAYER_HEALTH_REGEN=50

# penalty to player main core
PLAYER_HEALTH_CORE=4
PLAYER_STAMINA_CORE=12
PLAYER_DEADEYE_CORE=8

# penalty to player health outer core when main core is empty
PLAYER_HEALTH_PENALTY=4

# penalty to horse main core
HORSE_HEALTH_CORE=4
HORSE_STAMINA_CORE=8

# penalty to horse health outer core when main core is empty
HORSE_HEALTH_PENALTY=4

# penalty during aiming, when player temperature is hot, this is overidden buy how hot player is
STAMINA_AIMING_PENALTY=4
DEADEYE_AIMING_PENALTY=8

[TEMPERATURE_MODIFIER]
# Surrounding temperature affects player core mechanics, 0 disables this function
TEMPERATURE_CORE=1
TEMPERATURE_CORE_FX=1
TEMPERATURE_CORE_SPRITE=1

# accumulates to determine final amount of clothing needed for player, percentage based
# positive points for hot/warmness
FIRE_MODIFIER=50
CAMPFIRE_MODIFIER=50
INDOOR_MODIFIER=100

# negative points for coldness
SUBMERGED_MODIFIER=100 # adds up with submerge level
RAINING_MODIFIER=50 # adds up with rain level
SNOWING_MODIFIER=100 # adds up with snow level

# theses values get divided by 100 to represent threshold of player is cold or hot
# pointDifferences is differences of your clothing vs temperature with other modifiers
COLD_THRESHOLD=150 # simulate cold if pointDifferences is less than -1.5, say player is wearing 6.0 points of clothing vs 8.0 points of temperature, outfitModifier is cold, this will be converted to negative value
HOT_THRESHOLD=400 # simulate hot if pointDifferences is more or equal than 4.0, say player is wearing 10.0 points of clothing vs 6.0 points of temperature, outfitModifier is hot

[DEATH_PENALTY]
# overrides all configuration under DEATH_PENALTY, 0 disables all of below this function
PENALTY_ON_DEATH=1

# lose weapon on hand & its ammo, 0 disables this function
LOSE_HAND_WEAPON=1

# lose all weapon attached to body & its ammo, 0 disables this function
LOSE_BODY_WEAPON=1

# don't lose exotic weapon
LOSE_EXOTIC_WEAPON=1

# lose randomized amount of money within this range when died, 0 disables this function, you'll still lose money based on how the game handles it
LOSE_MONEY=1
LOWEST_MONEY_LOSE=50
HIGHEST_MONEY_LOSE=100

# percentage based 0 - 100 according to player health treshold
[DAMAGE_MODIFIER]
# overrides all configuration under DAMAGE_MODIFIER, 0 = disable all of below functions
DAMAGE_TWEAKS=0

# ai damage modifier, melee combat is 20% from this value
HIGHEST_AI_DAMAGE=300
HIGH_AI_DAMAGE=250
MEDIUM_AI_DAMAGE=200
LOW_AI_DAMAGE=150
LOWEST_AI_DAMAGE=100

# player damage modifier, melee combat is 20% from this value
HIGHEST_PLAYER_DAMAGE=80
HIGH_PLAYER_DAMAGE=70
MEDIUM_PLAYER_DAMAGE=60
LOW_PLAYER_DAMAGE=50
LOWEST_PLAYER_DAMAGE=40

# percentage based 0 - 100 according to ai health treshold
[AI_COMBAT_MODIFIER]
# overrides all configuration under AI_COMBAT_MODIFIER, 0 = disable all of below functions
AI_TWEAKS=1

# regen amount based on their hp
AI_REGEN=1
HIGHEST_HEALTH_REGEN=80
HIGH_HEALTH_REGEN=60
MEDIUM_HEALTH_REGEN=40
LOW_HEALTH_REGEN=20
LOWEST_HEALTH_REGEN=10

# accuracy amount based on their hp
AI_ACCURACY=1
HIGHEST_ACCURACY=100
HIGH_ACCURACY=90
MEDIUM_ACCURACY=80
LOW_ACCURACY=70
LOWEST_ACCURACY=60

# shootrate amount based on their hp
AI_SHOOT_RATE=1
HIGHEST_SHOOT_RATE=1000
HIGH_SHOOT_RATE=900
MEDIUM_SHOOT_RATE=800
LOW_SHOOT_RATE=700
LOWEST_SHOOT_RATE=600

# max is 1024, lower down this value if there's any noticable performance drop
[MOD_RANGE]
PEDS=1024
