### SoftCoresRevived Config ###

# Here you can disable vanilla game effects for immersion.
[VANILLA_FX]
# If false, all FX options are ignored and screen effects are left untouched (vanilla).
FXOverrideEnabled = true

EmptyHealthCoreFX = true
EmptyStaminaCoreFX = true
EmptyDeadeyeCoreFX = true
# Overpowered cores are golden cores.
OverpoweredCoreFX = true
DuelFX = true
DeadeyeFX = true
EagleeyeFX = true
WeaponWheelFX = false
KillCamFX = false
DeathFX = false
MissionFailFX = false

# Extra immersion features.
[IMMERSION]
DisableWeaponGlow = true
DisablePickupGlow = true
# Hide blips on the map when you cannot see their associated ped.
HideOutOfViewBlips = true
HideOutOfViewBlipsOnlyHostile = false
HideOutOfViewBlipsInMissions = false
HideOutOfViewBlipsForCorpses = false
NoAutoReloadInDeadeye = true
SleepOnlyRestoresStamina = true
BathOnlyRestoresDeadeye = true

### MAIN MOD FEATURES ###

# Core Reference:
#   Depletion:  Depletion refers to the gradual reduction of an INNER core.
#   Drain:      Drain refers to the gradual reduction of an OUTER core.

# Core depletion from various situations.
[CORE_DEPLETION]
# Toggle this feature.
CoreDepletion = true

# There are 3 types of depletion: Natural, Empty health core, and Temperature.
# Each type has it's own effects on the player's cores, and they do not modify eachother.

# Increased depletion of inner cores over time.
NaturalCoreDepletion = true
# Temperature mechanics for natural core depletion.
TemperatureDepletion = true
# Depletion of other cores while health core is empty.
HealthCoreEmptyDepletion = true

# Drain health outer core while health core empty, like a bleedout.
HealthCoreEmptyDrain = true

# Optional drain of outer cores while aiming.
AimingStaminaDrain = false
AimingDeadeyeDrain = false

### MULTIPLIERS
# Multiplier for the base depletion (affects all types).
BaseDepletionRate = 1.00

# Multipliers for individual cores (affects all types).
HealthCoreDepletionRate = 0.90
StaminaCoreDepletionRate = 1.00
DeadeyeCoreDepletionRate = 0.70

# Natural, always-active depletion of cores.
NaturalCoreDepletionRate = 1.00

# Depletion when too hot or too cold (further temperature configuration in the [TEMPERATURE] section).
TemperatureDepletionRate = 1.20

# Depletion when health core is empty.
HealthCoreEmptyDepletionRate = 2.00

# Bleedout.
HealthCoreDrainRate = 1.00

# Aiming.
AimingStaminaDrainRate = 1.00
AimingDeadeyeDrainRate = 1.00

# Core depletion from various situations, but for your horse.
[HORSE_CORE_DEPLETION]
# Toggle this feature.
HorseCoreDepletion = true

# Horses only have 2 depletion types: Natural and Empty health core.

# Increased depletion of inner cores over time.
HorseNaturalCoreDepletion = true
# Depletion of other cores while health core is empty.
HorseHealthCoreEmptyDepletion = true

### MULTIPLIERS
# Multiplier for the base depletion (affects all types).
HorseBaseDepletionRate = 1.00

# Multipliers for individual cores (affects all types).
HorseHealthCoreDepletionRate = 0.90
HorseStaminaCoreDepletionRate = 1.00

# Natural, always-active depletion of cores.
HorseNaturalCoreDepletionRate = 1.00

# Depletion when health core is empty.
HorseHealthCoreEmptyDepletionRate = 2.00

# Temperature settings. These only work if TemperatureMechanics is enabled in [CORE_DEPLETION]
[TEMPERATURE]
# Enables visual effect when too cold or too hot.
ExtremeTemperatureFX = true
# Enables small sprite on the hud to inidicate being too hot or too cold.
ExtremeTemperatureSprite = true

### MULTIPLIERS
# Warmth multipliers, these control how much warmth certain things give the player when in their proximity.
WarmthFire = 1.00
WarmthCampfire = 1.00
WarmthIndoors = 1.00

# Cold multipliers, these control how cold the player becomes from certain enviornmental conditions.
ColdSubmerged = 1.00
ColdRaining = 1.00
ColdSnowing = 1.20

# These multipliers change how easily the player reaches extreme temperature.
# Higher values mean its harder to become too hot or too cold.
FreezingThreshold = 1.00
HotThreshold = 1.00

# Several possible penalties to the player upon dying. By default, losing weapons is disabled.
[PENALTY_ON_DEATH]
# Toggle this feature.
PenaltyOnDeath = true

# Lose held weapon.
LoseHeldWeapon = false
# Lose held weapon's ammo.
LoseHeldAmmo = false
# Lose all weapons on body.
LoseBodyWeapons = false
# Lose ammo of all weapons on body.
LoseBodyAmmo = false
# Allow losing unique/exotic weapons (unrecoverable without a trainer).
LoseExoticWeapons = false

# Lose money.
LoseMoney = true
# Minimum proportion of money to lose.
LoseMoneyMin = 0.90
# Maximum proportion of money to lose.
LoseMoneyMax = 0.98
# Maximum money to lose (in dollars).
LoseMoneyHardMax = 1000000
# Minimum money to be left with (in dollars).
LoseMoneyHardMin = 0

# Tweaks to player combat.
[PLAYER_COMBAT_TWEAKS]
# Toggle this feature.
PlayerCombatTweaks = false

# Player damage multipliers based on their health (inner core).
PlayerDamageMaxHealth = 1.00
PlayerDamageMinHealth = 0.50

# Tweaks to AI combat.
[AI_COMBAT_TWEAKS]
# Toggle this feature.
AICombatTweaks = false

# AI damage adjustments.
AIDamageTweaks = true
# AI health regeneration.
AIHealthRegeneration = false
# AI accuracy changes.
AIAccuracyTweaks = true
# A lot of missions throw a bunch of enemies at you, making them really hard with high enemy accuracy. Enable this option to force vanilla accuracy during missions.
AIAccuracyTweaksInMissions = false
# AI firerate changes.
AIFirerateTweaks = true

# AI damage multipliers based on their health.
AIDamageMaxHealth = 1.00
AIDamageMinHealth = 0.50

# AI regeneration multipliers based on their health.
AIHealthRegenerationMaxHealth = 1.00
AIHealthRegenerationMinHealth = 0.10

# AI accuracy multipliers based on their health.
AIAccuracyMaxHealth = 0.80
AIAccuracyMinHealth = 0.05

# AI firerate multipliers based on their health.
AIFirerateMaxHealth = 1.00
AIFirerateMinHealth = 0.10

[DEBUG]

# Maximum peds for calculations, ONLY lower this if you are absolutely sure the mod is causing performance issues.
# Max: 1024.
PerfMaxPeds = 1024
# Development debug logging, should only be used for debugging as it degrades performance.
ForceDebugLogging = false
IngameDebugLogging = false
