### SoftCoresRevived Config ###

# Enable or disable base game screen effects.
[VANILLA_FX]
# If false, all FX options are ignored and screen effects are left untouched (vanilla).
FXOverrideEnabled = true

EmptyHealthCoreFX = true
EmptyStaminaCoreFX = true
EmptyDeadeyeCoreFX = true
OverpoweredCoreFX = true # Overpowered cores are golden cores.
DuelFX = true
DeadeyeFX = true
EagleeyeFX = true
WeaponWheelFX = false
KillCamFX = false
DeathFX = false
MissionFailFX = false

# Extra immersion features.
[IMMERSION]
DisablePickupGlow = true
DisableObjectGlow = true
HideHostileBlipsOutOfView = true
HideHostileBlipsOutOfViewInMissions = false
NoReloadInDeadeye = true
SleepOnlyRestoresStamina = true
BathOnlyRestoresDeadeye = true

### MAIN MOD FEATURES ###

# Core depletion from various situations.
[CORE_DEPLETION]
# Toggle this feature.
CoreDepletion = true

# Increased depletion of inner cores over time.
NaturalCoreDepletionEnabled = true
# Temperature mechanics for natural core depletion.
TemperatureMechanics = true
# Health outer core depletion while inner core empty (like a bleedout).
HealthCoreEmptyBleedout = true
# Outer core depletion while aiming.
AimingStaminaPenalty = false
AimingDeadeyePenalty = false

### MULTIPLIERS
# Base depletion of all cores (this affects the mod's own depletion, not vanilla).
NaturalCoreDepletion = 1.00

# Multipliers for individual cores.
HealthCoreDepletion = 0.90
StaminaCoreDepletion = 1.00
DeadeyeCoreDepletion = 0.70

# These are multipliers to the NaturalCoreDepletion rate of all cores when in certain situations.
ExtremeTemperatureDepletion = 1.10
HealthCoreEmptyDepletion = 2.00

# Outer core depletion.
HealthCoreBleedoutRate = 1.00
AimingStaminaDepletion = 1.00
AimingDeadeyeDepletion = 1.00

# Core depletion from various situations, but for your horse.
[HORSE_CORE_DEPLETION]
# Toggle this feature.
HorseCoreDepletion = true

# Increased depletion of inner cores over time.
HorseNaturalCoreDepletionEnabled = true

### MULTIPLIERS
# Base depletion of all cores (this affects the mod's own depletion, not vanilla).
HorseNaturalCoreDepletion = 1.00

# Multipliers for individual cores.
HorseHealthCoreDepletion = 0.90
HorseStaminaCoreDepletion = 1.00

# These are multipliers to the HorseNaturalCoreDepletion rate of all cores when in certain situations.
HorseHealthCoreEmptyDepletion = 2.00

# Temperature settings. These only work if TemperatureMechanics is enabled in [CORE_DEPLETION]
[TEMPERATURE]
# Enables visual effect when too cold or too hot.
ExtremeTemperatureFX = true
# Enables small sprite on the hud to inidicate being too hot or too cold.
ExtremeTemperatureSprite = true

### MULTIPLIERS
# Warmth multipliers, these control how much warmth certain things give the player when in their proximity.
WarmthFire = 1.00
WarmthCampfire = 1.00
WarmthIndoors = 1.00

# Cold multipliers, these control how cold the player becomes from certain enviornmental conditions.
ColdSubmerged = 1.00
ColdRaining = 1.00
ColdSnowing = 1.20

# These multipliers change how easily the player reaches extreme temperature.
# Higher values mean its harder to become too hot or too cold.
ColdThreshold = 1.00
HotThreshold = 1.00

# Several possible penalties to the player upon dying. By default, losing weapons is disabled.
[PENALTY_ON_DEATH]
# Toggle this feature.
PenaltyOnDeath = true

# Lose held weapon.
LoseHeldWeapon = false
# Lose held weapon's ammo.
LoseHeldAmmo = false
# Lose all weapons on body.
LoseBodyWeapons = false
# Lose ammo of all weapons on body.
LoseBodyAmmo = false
# Allow losing unique/exotic weapons (unrecoverable without a trainer).
LoseExoticWeapons = false

# Lose money.
LoseMoney = true
# Minimum proportion of money to lose.
LoseMoneyMinimum = 0.90
# Maximum proportion of money to lose.
LoseMoneyMaximum = 0.98
# Maximum money to lose (in dollars).
LoseMoneyHardMaximum = 1000000
# Minimum money to be left with (in dollars).
LoseMoneyHardMinimum = 0

# Tweaks to player combat.
[PLAYER_COMBAT_TWEAKS]
# Toggle this feature.
PlayerCombatTweaks = false

# Player damage multipliers based on their health (inner core).
PlayerDamageMaxHealth = 1.00
PlayerDamageMinHealth = 0.50

# Tweaks to AI combat.
[AI_COMBAT_TWEAKS]
# Toggle this feature.
AICombatTweaks = false

# AI damage adjustments.
AIDamageTweaks = true
# AI health regeneration.
AIHealthRegeneration = false
# AI accuracy changes.
AIAccuracyTweaks = true
# A lot of missions throw a bunch of enemies at you, making them really hard with high enemy accuracy. Enable this option to force vanilla accuracy during missions.
AIAccuracyTweaksInMissions = false
# AI firerate changes.
AIFirerateTweaks = true

# AI damage multipliers based on their health.
AIDamageMaxHealth = 1.00
AIDamageMinHealth = 0.50

# AI regeneration multipliers based on their health.
AIHealthRegenerationMaxHealth = 1.00
AIHealthRegenerationMinHealth = 0.10

# AI accuracy multipliers based on their health.
AIAccuracyMaxHealth = 0.80
AIAccuracyMinHealth = 0.05

# AI firerate multipliers based on their health.
AIHealthRegenerationMaxHealth = 1.00
AIHealthRegenerationMinHealth = 0.10

[DEBUG]

# Maximum peds for calculations, only lower this if you are absolutely sure the mod is causing performance issues.
PerfMaxPeds = 1024
# Enable ingame logging, only enable for debugging, shows debug messages on hud.
DebugAdvancedLogging = 1
