#pragma once

#include <string>
#include <array>
#include "types.h"

namespace SoftCores
{
	namespace Keys
	{
		class Key
		{
		public:
			std::string	keyString;

			Key(std::string str);
			Key(const char *str);
			Hash		Hash();
			const char	*ToCString();
		};

		Hash	GetHash(const char *str);

		const std::array<Key, 15>	CampScenarios = {
			"WORLD_PLAYER_CAMP_FIRE_KNEEL1",
			"WORLD_PLAYER_CAMP_FIRE_KNEEL2",
			"WORLD_PLAYER_CAMP_FIRE_KNEEL3",
			"WORLD_PLAYER_CAMP_FIRE_KNEEL4",
			"WORLD_PLAYER_CAMP_FIRE_SIT",
			"WORLD_PLAYER_CAMP_FIRE_SQUAT",
			"WORLD_PLAYER_DYNAMIC_KNEEL_KNIFE",
			"WORLD_PLAYER_CAMP_FIRE_SQUAT_MALE_A",
			"WORLD_PLAYER_CAMP_FIRE_SIT_MALE_A",
			"WORLD_PLAYER_DYNAMIC_CAMP_FIRE_KNEEL_ARTHUR",
			"PROP_PLAYER_SLEEP_TENT_A_FRAME",
			"PROP_PLAYER_SEAT_CHAIR_PLAYER_CAMP",
			"PROP_PLAYER_SEAT_CHAIR_DYNAMIC",
			"PROP_PLAYER_SEAT_CHAIR_GENERIC",
			"PROP_PLAYER_SEAT_CHAIR_GENERIC_CA"
		};

		const std::array<Key, 11>	SleepScenarios = {
			"WORLD_PLAYER_SLEEP_BEDROLL",
			"WORLD_PLAYER_SLEEP_BEDROLL_ARTHUR",
			"WORLD_PLAYER_SLEEP_GROUND",
			"PROP_PLAYER_SLEEP_BED",
			"PROP_PLAYER_SLEEP_BED_ARTHUR",
			"PROP_PLAYER_SLEEP_TENT_A_FRAME",
			"PROP_PLAYER_SLEEP_TENT_A_FRAME_ARTHUR",
			"PROP_PLAYER_SLEEP_TENT_MALE_A",
			"PROP_PLAYER_SLEEP_TENT_MALE_A_ARTHUR",
			"PROP_PLAYER_SLEEP_A_FRAME_TENT_PLAYER_CAMPS",
			"PROP_PLAYER_SLEEP_A_FRAME_TENT_PLAYER_CAMPS_ARTHUR"
		};

		const std::array<Key, 8>	StoryPostFXs = {
			"ODR3_Injured01Loop",
			"ODR3_Injured02Loop",
			"ODR3_Injured03Loop",
			"PlayerHealthPoorGuarma",
			"PlayerSickDoctorsOpinion",
			"PlayerSickDoctorsOpinionOutBad",
			"PlayerSickDoctorsOpinionOutGood",
			"PlayerWakeUpInterrogation"
		};

		const std::array<Key, 44>	FriendlyPeds = {
			"CS_ABIGAILROBERTS",
			"CS_BEATENUPCAPTAIN",
			"CS_BILLWILLIAMSON",
			"CS_BROTHERDORKINS",
			"CS_CAPTAINMONROE",
			"CS_CHARLESSMITH",
			"CS_CLAY",
			"CS_CLEET",
			"CS_CLIVE",
			"CS_DUTCH",
			"CS_EAGLEFLIES",
			"CS_EDITHDOWN",
			"CS_HAMISH",
			"CS_HERCULE",
			"CS_HOSEAMATTHEWS",
			"CS_JACKMARSTON",
			"CS_JACKMARSTON_TEEN",
			"CS_JAMIE",
			"CS_JAVIERESCUELLA",
			"CS_JOE",
			"CS_JOHNMARSTON",
			"CS_JOSIAHTRELAWNY",
			"CS_JULES",
			"CS_KAREN",
			"CS_LEMIUXASSISTANT",
			"CS_LENNY",
			"CS_LEON",
			"CS_LEOSTRAUSS",
			"CS_MAGNIFICO",
			"CS_MARYBETH",
			"CS_MICAHBELL",
			"CS_MOLLYOSHEA",
			"CS_MRPEARSON",
			"CS_MRSADLER",
			"CS_PAYTAH",
			"CS_PRINCESSISABEAU",
			"CS_RAINSFALL",
			"CS_REVSWANSON",
			"CS_SEAN",
			"CS_SISTERCALDERON",
			"CS_SUSANGRIMSHAW",
			"CS_THOMASDOWN",
			"CS_TILLY",
			"CS_UNCLE"
		};

		const std::array<Key, 16>	ItemWeapons = {
			"WEAPON_UNARMED",
			"WEAPON_MELEE_LANTERN",
			"WEAPON_MELEE_DAVY_LANTERN",
			"WEAPON_MELEE_LANTERN_ELECTRIC",
			"WEAPON_KIT_BINOCULARS",
			"WEAPON_KIT_CAMERA",
			"WEAPON_KIT_DETECTOR",
			"WEAPON_BOW_CHARLES",
			"WEAPON_BOW",
			"WEAPON_FISHINGROD",
			"WEAPON_LASSO",
			"WEAPON_KIT_CAMERA_ADVANCED",
			"WEAPON_BOW_IMPROVED",
			"WEAPON_LASSO_REINFORCED",
			"WEAPON_KIT_BINOCULARS_IMPROVED",
			"WEAPON_MOONSHINEJUG_MP"
		};

		const std::array<Key, 11>	ExoticWeapons = {
			"WEAPON_REVOLVER_DOUBLEACTION_GAMBLER",
			"WEAPON_REVOLVER_CATTLEMAN_MEXICAN",
			"WEAPON_REVOLVER_CATTLEMAN_PIG",
			"WEAPON_REVOLVER_DOUBLEACTION_EXOTIC",
			"WEAPON_REVOLVER_SCHOFIELD_GOLDEN",
			"WEAPON_PISTOL_MAUSER_DRUNK",
			"WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC",
			"WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC",
			"WEAPON_REVOLVER_CATTLEMAN_JOHN",
			"WEAPON_REVOLVER_DOUBLEACTION_MICAH",
			"WEAPON_REVOLVER_SCHOFIELD_CALLOWAY"
		};

		const std::array<Key, 8>	ThrowableWeapons {
			"WEAPON_THROWN_DYNAMITE",
			"WEAPON_THROWN_MOLOTOV",
			"WEAPON_THROWN_THROWING_KNIVES_JAVIER",
			"WEAPON_THROWN_THROWING_KNIVES",
			"WEAPON_THROWN_TOMAHAWK",
			"WEAPON_THROWN_TOMAHAWK_ANCIENT",
			"WEAPON_THROWN_BOLAS",
			"WEAPON_THROWN_POISONBOTTLE"
		};

		const std::array<Key, 13>	MeleeWeapons = {
			"WEAPON_MELEE_HATCHET_MELEEONLY",
			"WEAPON_MELEE_KNIFE",
			"WEAPON_MELEE_KNIFE_CIVIL_WAR",
			"WEAPON_MELEE_BROKEN_SWORD",
			"WEAPON_MELEE_HATCHET",
			"WEAPON_MELEE_HATCHET_HEWING",
			"WEAPON_MELEE_ANCIENT_HATCHET",
			"WEAPON_MELEE_HATCHET_HUNTER",
			"WEAPON_MELEE_HATCHET_VIKING",
			"WEAPON_MELEE_HATCHET_DOUBLE_BIT_RUSTED",
			"WEAPON_MELEE_HATCHET_DOUBLE_BIT",
			"WEAPON_MELEE_HATCHET_HUNTER_RUSTED",
			"WEAPON_MELEE_CLEAVER"
		};
	}
}
